// This was generated by ChatGPT and needs serious corretion

import React, { useState } from "react";

const Task = ({ task, allTasks, onAddTask, onUpdate }) => {
  const [completed, setCompleted] = useState(task.completed);

  // Find subTasks by parentTaskID
  const subTasks = allTasks.filter((t) => t.parentTaskID === task.taskID);

  const allSubTasksCompleted = subTasks.every((st) => st.completed);

  const handleMarkCompleted = () => {
    if (!allSubTasksCompleted) {
      alert("Complete all subTasks first!");
      return;
    }
    setCompleted(true);
    onUpdate({ ...task, completed: true });
  };

  const handleAddSubTask = (title, description) => {
    const newSubTask = {
      taskID: Date.now().toString(),
      title,
      description,
      completed: false,
      parentTaskID: task.taskID,
    };
    onAddTask(newSubTask);
  };

  return (
    <div style={{ border: "1px solid gray", padding: "10px", margin: "5px" }}>
      <h3>{task.title}</h3>
      <p>{task.description}</p>

      <button
        onClick={handleMarkCompleted}
        disabled={completed || !allSubTasksCompleted}
      >
        {completed ? "Completed" : "Mark Complete"}
      </button>

      <SubTaskForm onAdd={handleAddSubTask} />

      {subTasks.length > 0 && (
        <div style={{ marginTop: "10px" }}>
          <h4>SubTasks:</h4>
          <ul>
            {subTasks.map((st) => (
              <li key={st.taskID}>
                {st.title} - {st.completed ? "✅" : "❌"}
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
};

const SubTaskForm = ({ onAdd }) => {
  const [title, setTitle] = React.useState("");
  const [description, setDescription] = React.useState("");

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!title) return;

    onAdd(title, description);

    setTitle("");
    setDescription("");
  };

  return (
    <form onSubmit={handleSubmit} style={{ marginTop: "5px" }}>
      <input
        type="text"
        placeholder="SubTask title"
        value={title}
        onChange={(e) => setTitle(e.target.value)}
      />
      <input
        type="text"
        placeholder="SubTask description"
        value={description}
        onChange={(e) => setDescription(e.target.value)}
      />
      <button type="submit">Add SubTask</button>
    </form>
  );
};

export default Task;
