// This was generated by ChatGPT and needs serious corretion

import React from "react";

const ToDoList = ({ tasks, onAddTask }) => {
  const completedCount = tasks.filter((t) => t.completed).length;

  return (
    <div style={{ border: "2px solid black", padding: "10px", margin: "10px" }}>
      <h2>ToDoList</h2>
      <p>
        Progress: {completedCount} / {tasks.length}
      </p>

      <h3>Tasks:</h3>
      <ul>
        {tasks.map((task) => (
          <li key={task.taskID}>{task.title}</li>
        ))}
      </ul>

      <AddTaskForm onAddTask={onAddTask} />
    </div>
  );
};

const AddTaskForm = ({ onAddTask }) => {
  const [title, setTitle] = React.useState("");
  const [description, setDescription] = React.useState("");

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!title) return;

    onAddTask({
      taskID: Date.now().toString(),
      title,
      description,
      completed: false,
      parentTaskID: null,
    });

    setTitle("");
    setDescription("");
  };

  return (
    <form onSubmit={handleSubmit} style={{ marginTop: "10px" }}>
      <input
        type="text"
        placeholder="Task title"
        value={title}
        onChange={(e) => setTitle(e.target.value)}
      />
      <input
        type="text"
        placeholder="Task description"
        value={description}
        onChange={(e) => setDescription(e.target.value)}
      />
      <button type="submit">Add Task</button>
    </form>
  );
};

export default ToDoList;
