// This was generated by ChatGPT and needs serious corretion

import React, { useState } from "react";
import ToDoList from "./components/ToDoList.jsx";
import Task from "./components/Task.jsx";

function App() {
  const [tasks, setTasks] = useState([]);

  // Add a new Task or SubTask
  const handleAddTask = (newTask) => {
    setTasks([...tasks, newTask]);
  };

  // Update a Task (or SubTask)
  const handleUpdateTask = (updatedTask) => {
    setTasks(
      tasks.map((t) => (t.taskID === updatedTask.taskID ? updatedTask : t)),
    );
  };

  return (
    <div>
      <ToDoList
        tasks={tasks.filter((t) => !t.parentTaskID)}
        onAddTask={handleAddTask}
      />

      <h2>All Tasks</h2>
      {tasks.map((task) => (
        <Task
          key={task.taskID}
          task={task}
          allTasks={tasks}
          onAddTask={handleAddTask}
          onUpdate={handleUpdateTask}
        />
      ))}
    </div>
  );
}

export default App;
